name: Build binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  prepare:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      publish-version: ${{ steps.set-version.outputs.publish_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version from tag
        run: |
          PUBLISH_VERSION="${GITHUB_REF_NAME:1}"
          echo "publish_version=$PUBLISH_VERSION" >> $GITHUB_ENV

      - name: Set version to outputs
        id: set-version
        run: |
          echo "::set-output name=publish_version::${{ env.publish_version }}"
          echo "version: ${{ env.publish_version }}"

  macos:
    name: Build macos binary
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: gradle

      - name: Build binary
        run: ./gradlew --no-daemon build

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: executable
          path: build/bin/macosX64/releaseExecutable/hotvay.kexe

  release:
    name: Release binaries
    needs: [ prepare, macos ]
    runs-on: ubuntu-latest
    steps:
      - name: Get version from tag
        run: |
          PUBLISH_VERSION="${GITHUB_REF_NAME:1}"
          echo "publish_version=$PUBLISH_VERSION" >> $GITHUB_ENV
          echo "version: $PUBLISH_VERSION"

      - name: Download binaries from build
        uses: actions/download-artifact@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: Upload macos binary
        id: upload_macos_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: executable/hotvay.kexe
          asset_name: hotvay-v${{ env.publish_version }}
          asset_content_type: application/x-executable
